### ISSUE TITLE
Lots of vulns 

### ISSUE THREAD

**Issue by AkshayJainG** [fluxbb/fluxbb#173]
http://php-grinder.com/project/view/18700

**Comment by adaur** [comment]
Are these even vulnerabilities?

**Comment by franzliedke** [comment]
I don't think so. This seems to be some kind of automated scanner that apparently makes mistakes...

@AkshayJainG Can you explain where exactly the vulnerabilities are?

(And why is the issue tracker suddenly enabled on this repo? That shouldn't be the case...)

**Comment by oldskool** [comment]
Seems to me like an automated process that tags **potential** security risks. Although in most cases (haven't checked every single one) it's not really a vulnerability, because input has already been sanitised or checked at that point. So I don't really see any critical issues here.

**Comment by AkshayJainG** [comment]
I am using this in one of my projects and i read about it on reddit. So I
thought of reporting it you.

**Comment by franzliedke** [comment]
Okay, thanks. I've reviewed these and found no issues.

I'm closing this. Please use [our own issue tracker](https://fluxbb.org/development/core/tickets/) for further reports.
